### ISSUE TITLE
Project Housekeeping: Create Checklist for New Projects / Updating Existing Projects

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/bootstrap#121]
Purpose of this checklist is to help onboard new projects as well as ensure that existing projects have updated their resources to reflect the new foundation:

- [ ] Select CLA or DCO
- [ ] Move / Update JSF cla-bot (see #124 )
- [ ] Use of OpenJS Foundation logo on website
- [ ] Reference 'PROJECT NAME' is an OpenJS Foundation Project'
- [ ] Disclaimer on any crowdfunding page
- [ ] transfer domains (+ other infra tasks)

...etc

**Comment by boneskull** [comment]
- [ ] update copyright notices

**Comment by mhdawson** [comment]
- [ ] Adopt Common Code of Conduct
- [ ] Update moderation procedures to reflect escalation procedures
- [ ] Identify/support members who want to join CPC
- [ ] Document contacts and how to contact Foundation resources for 
  - for social/marking/etc
  - etc.

**Comment by Trott** [comment]
Node.js Foundation has a travel budget which the board grants jointly to the Node.js Technical Steering Committee and Community Committee for administration. Figure out if that thing is going to continue being a Node.js project fund or if it is something to be used more broadly for the entire OpenJS Foundation. If the latter, then determinations will need to be made about how it is administered.

**Comment by Trott** [comment]
Whoops, wrong issue. I'll delete that above and this comment. Sorry!

**Comment by amiller-gh** [comment]
Action item for me from today's meeting: PR a stage 1 proposal for new project on-boarding capturing this checklist. Existing projects can dogfood this list for bootstrap.
